/**
 * Cypher export module — generates Neo4j 5.x Cypher scripts from OAA v6 ontologies.
 * Handles both v5 (array entities) and v6.2.0 (object-keyed entities) formats.
 */

import { state } from './state.js';

// --- Helpers ---

export function escCypher(str) {
  if (!str) return '';
  return String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, ' ');
}

export function toNeo4jLabel(entityId) {
  if (!entityId) return 'Unknown';
  // Handle full URIs — extract local part
  if (entityId.includes('//')) {
    const frag = entityId.split('/').pop();
    return frag.replace(/[^a-zA-Z0-9_]/g, '_');
  }
  if (entityId.includes(':')) {
    const idx = entityId.indexOf(':');
    const prefix = entityId.slice(0, idx);
    const local = entityId.slice(idx + 1);
    return `${prefix.toUpperCase()}_${local}`;
  }
  return entityId.replace(/[^a-zA-Z0-9_]/g, '_');
}

export function toRelType(name, edgeType) {
  if (edgeType === 'inheritance' || name === 'subClassOf' || name === 'rdfs:subClassOf') return 'IS_A';
  if (edgeType === 'binding') return 'BOUND_TO';
  // camelCase → UPPER_SNAKE_CASE
  return (name || 'RELATES_TO')
    .replace(/^[a-z]+:/, '')          // strip namespace prefix
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .toUpperCase();
}

export function toCypherVar(entityId) {
  if (!entityId) return 'unknown';
  return entityId
    .replace(/.*[/]/, '')             // strip URI base
    .replace(':', '_')
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .toLowerCase();
}

export function extractEntityProperties(entity) {
  const props = [];

  // OAA v5: array format
  const propsArray = entity['oaa:properties'] ||
    (Array.isArray(entity.properties) ? entity.properties : null);
  if (propsArray) {
    for (const p of propsArray) {
      props.push({
        name: p.name,
        type: p.type || 'string',
        required: !!p.required,
        description: p.description || ''
      });
    }
    return props;
  }

  // OAA v6.2.0: object-keyed format
  if (entity.properties && typeof entity.properties === 'object' && !Array.isArray(entity.properties)) {
    for (const [name, spec] of Object.entries(entity.properties)) {
      if (typeof spec === 'object' && spec !== null) {
        props.push({
          name,
          type: spec.type || 'string',
          required: !!spec.required,
          description: spec.description || ''
        });
      }
    }
  }
  return props;
}

export function getRawEntities(data) {
  let entities = data.entities || data.hasDefinedTerm ||
    (data.ontologyDefinition && data.ontologyDefinition.entities) || [];
  if (!Array.isArray(entities) && typeof entities === 'object') {
    return Object.entries(entities).map(([key, val]) => ({
      _key: key,
      ...(typeof val === 'object' && val !== null ? val : {})
    }));
  }
  return Array.isArray(entities) ? entities : [];
}

export function getRawRelationships(data) {
  return data.relationships ||
    (data.ontologyDefinition && data.ontologyDefinition.relationships) || [];
}

// --- Section builders ---

function buildHeader(data, parsed) {
  const name = data.name || data['rdfs:label'] || parsed.name || 'Untitled Ontology';
  const oaaVer = data['oaa:schemaVersion'] || data.oaaVersion || 'unknown';
  const modVer = data['oaa:moduleVersion'] || data.version || 'unknown';
  const ts = new Date().toISOString();

  return [
    '// ============================================================',
    `// ${escCypher(name)} — Neo4j Graph Schema`,
    '// Generated by OAA Visualiser (Cypher Export)',
    `// OAA Version: ${oaaVer}  |  Module Version: ${modVer}`,
    `// Generated: ${ts}`,
    '// ============================================================',
    ''
  ].join('\n');
}

function buildConstraints(rawEntities) {
  if (!rawEntities.length) return '';
  const lines = ['// --- CONSTRAINTS ---', ''];
  for (const entity of rawEntities) {
    const id = entity['@id'] || entity._key || '';
    if (!id) continue;
    const label = toNeo4jLabel(id);
    const constraintName = label.toLowerCase().replace(/[^a-z0-9_]/g, '_') + '_id';
    lines.push(`CREATE CONSTRAINT ${constraintName} IF NOT EXISTS`);
    lines.push(`FOR (n:${label}) REQUIRE n.id IS UNIQUE;`);
    lines.push('');
  }
  return lines.join('\n');
}

function buildImportMerges(data) {
  const imports = data['oaa:imports'] ||
    (data.ontologyDefinition && data.ontologyDefinition['oaa:imports']) || [];
  if (!imports.length) return '';

  const lines = ['// --- IMPORTED ENTITIES (MERGE — idempotent) ---', ''];
  for (const imp of imports) {
    const sourceName = imp.name || imp['@id'] || 'unknown';
    const sourceVersion = imp.version || 'unknown';
    const imported = imp.importedEntities || [];
    for (const entityId of imported) {
      const label = toNeo4jLabel(entityId);
      lines.push(`MERGE (n:${label} { id: '${escCypher(entityId)}', source: '${escCypher(sourceName)}', version: '${escCypher(sourceVersion)}' });`);
    }
    const importedRels = imp.importedRelationships || [];
    if (importedRels.length) {
      lines.push(`// Imported relationships from ${escCypher(sourceName)}: ${importedRels.join(', ')}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function buildEntityStatements(rawEntities) {
  if (!rawEntities.length) return '';
  const lines = ['// --- ENTITIES ---', ''];

  for (const entity of rawEntities) {
    const id = entity['@id'] || entity._key || '';
    if (!id) continue;

    const label = toNeo4jLabel(id);
    const varName = toCypherVar(id);
    const name = entity.name || entity['rdfs:label'] || id.split(':').pop();
    const description = entity.description || entity['rdfs:comment'] || '';
    const subClassOf = entity['rdfs:subClassOf'] || entity.subClassOf || '';

    const props = extractEntityProperties(entity);
    const propLines = [
      `  id: '${escCypher(id)}'`,
      `  name: '${escCypher(name)}'`
    ];
    if (description) {
      propLines.push(`  description: '${escCypher(description)}'`);
    }
    if (subClassOf) {
      propLines.push(`  subClassOf: '${escCypher(typeof subClassOf === 'string' ? subClassOf : JSON.stringify(subClassOf))}'`);
    }
    for (const p of props) {
      const comment = [p.type, p.required ? 'required' : ''].filter(Boolean).join(', ');
      propLines.push(`  ${p.name}: ''  // ${comment}`);
    }

    lines.push(`CREATE (${varName}:${label} {`);
    lines.push(propLines.join(',\n'));
    lines.push('});');
    lines.push('');
  }
  return lines.join('\n');
}

function buildRelationshipStatements(rawRels, rawEntities, parsedEdges) {
  // Build entity lookup by @id for label resolution
  const entityMap = new Map();
  for (const e of rawEntities) {
    const id = e['@id'] || e._key || '';
    if (id) entityMap.set(id, e);
  }

  // Use raw relationships if available (richer data), fall back to parsed edges
  const rels = rawRels.length ? rawRels : null;
  const lines = ['// --- RELATIONSHIPS ---', ''];

  if (rels) {
    for (const rel of rels) {
      // Resolve source and target from both v5 and v6.2.0 formats
      const sources = rel.sourceEntity ? [rel.sourceEntity] :
        (rel.domainIncludes || rel['oaa:domainIncludes'] || []);
      const targets = rel.targetEntity ? [rel.targetEntity] :
        (rel.rangeIncludes || rel['oaa:rangeIncludes'] || []);
      const sourceArr = Array.isArray(sources) ? sources : [sources];
      const targetArr = Array.isArray(targets) ? targets : [targets];

      const relName = rel.name || rel['@id'] || rel.relationshipId || 'relatesTo';
      const relType = toRelType(relName, '');
      const cardinality = rel['oaa:cardinality'] || rel.cardinality || '';

      for (const src of sourceArr) {
        for (const tgt of targetArr) {
          const srcLabel = toNeo4jLabel(src);
          const tgtLabel = toNeo4jLabel(tgt);
          const relProps = cardinality ? ` { cardinality: '${escCypher(cardinality)}' }` : '';

          lines.push(`MATCH (a:${srcLabel} { id: '${escCypher(src)}' })`);
          lines.push(`MATCH (b:${tgtLabel} { id: '${escCypher(tgt)}' })`);
          lines.push(`CREATE (a)-[:${relType}${relProps}]->(b);`);
          lines.push('');
        }
      }
    }
  } else if (parsedEdges.length) {
    // Fallback to parsed edges
    for (const edge of parsedEdges) {
      const srcLabel = toNeo4jLabel(edge.from);
      const tgtLabel = toNeo4jLabel(edge.to);
      const relType = toRelType(edge.label, edge.edgeType);

      lines.push(`MATCH (a:${srcLabel} { id: '${escCypher(edge.from)}' })`);
      lines.push(`MATCH (b:${tgtLabel} { id: '${escCypher(edge.to)}' })`);
      lines.push(`CREATE (a)-[:${relType}]->(b);`);
      lines.push('');
    }
  }

  // Inheritance edges (subClassOf) from raw entities
  for (const entity of rawEntities) {
    const id = entity['@id'] || entity._key || '';
    const parent = entity['rdfs:subClassOf'] || entity.subClassOf || '';
    if (!id || !parent || typeof parent !== 'string') continue;

    const childLabel = toNeo4jLabel(id);
    const parentLabel = toNeo4jLabel(parent);
    lines.push(`// Inheritance`);
    lines.push(`MATCH (child:${childLabel} { id: '${escCypher(id)}' })`);
    lines.push(`MERGE (parent:${parentLabel} { id: '${escCypher(parent)}' })`);
    lines.push(`CREATE (child)-[:IS_A]->(parent);`);
    lines.push('');
  }

  return lines.join('\n');
}

function buildJoinPatternComments(data) {
  const patterns = data['oaa:joinPatterns'] ||
    (data.ontologyDefinition && data.ontologyDefinition['oaa:joinPatterns']) || [];
  if (!patterns.length) return '';

  const lines = ['// --- JOIN PATTERN QUERIES (informational) ---', ''];
  for (const jp of patterns) {
    const id = jp.patternId || jp['@id'] || '';
    const name = jp.name || '';
    const path = jp.joinPath || '';
    const useCase = jp.useCase || '';

    lines.push(`// ${id}: ${escCypher(name)}`);
    if (path) lines.push(`// Path: ${escCypher(path)}`);
    if (useCase) lines.push(`// Use case: ${escCypher(useCase)}`);
    lines.push('');
  }
  return lines.join('\n');
}

function buildBusinessRuleComments(data) {
  const rules = data.businessRules ||
    (data.ontologyDefinition && data.ontologyDefinition.businessRules) || [];
  if (!rules.length) return '';

  const lines = ['// --- BUSINESS RULES (constraint stubs) ---', ''];
  for (const rule of rules) {
    const id = rule.ruleId || rule['@id'] || '';
    const name = rule.name || '';
    const severity = rule.severity || 'warning';
    const condition = rule.condition || '';
    const action = rule.action || '';

    lines.push(`// ${id}: ${escCypher(name)} [${severity}]`);
    if (condition) lines.push(`// IF ${escCypher(condition)}`);
    if (action) lines.push(`// THEN ${escCypher(action)}`);

    if (severity.toLowerCase() === 'critical' || severity.toLowerCase() === 'error') {
      lines.push(`// APOC stub: CALL apoc.trigger.add('${escCypher(id)}', '<match-pattern>', {phase: 'before'})`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

// --- Main orchestrator ---

export function generateCypherScript(currentData, parsed) {
  if (!currentData || !parsed) return '';

  const rawEntities = getRawEntities(currentData);
  const rawRels = getRawRelationships(currentData);

  let cypher = '';
  cypher += buildHeader(currentData, parsed);
  cypher += buildConstraints(rawEntities);
  cypher += buildImportMerges(currentData);
  cypher += buildEntityStatements(rawEntities);
  cypher += buildRelationshipStatements(rawRels, rawEntities, parsed.edges || []);
  cypher += buildJoinPatternComments(currentData);
  cypher += buildBusinessRuleComments(currentData);

  return cypher;
}

// --- Public export function ---

export function exportCypher() {
  if (!state.lastParsed || !state.currentData) return '';

  const cypher = generateCypherScript(state.currentData, state.lastParsed);
  if (!cypher) return '';

  const fileName = document.getElementById('file-name')?.textContent || 'ontology';
  const baseName = fileName.replace(/\.json$/i, '').replace(/\s+/g, '-').toLowerCase();
  const blob = new Blob([cypher], { type: 'application/x-cypher-query' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${baseName}-graph-schema.cypher`;
  a.click();
  URL.revokeObjectURL(url);

  return cypher;
}
